version: '3.8'
services:
#  flask-container:
#    build: ./flask
#    container_name: flask-container
#    restart: always
#    environment:
#      - APP_NAME=MyFlaskApp
#    ports:
#      - 8080:8080

  flask-container:
    build: ./sql_app  # .
    container_name: flask-container
    command: uvicorn sql_app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
      #- DATABASE_URL=postgresql://fastapi:fastapi@db/fastapi
    #volumes:
    #  - ./:/src/
    ports:
      - 8080:8080

  postgresql-container:
    image: postgres:14
    container_name: postgresql-container
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - '5433:5432'
    volumes:
      - postgresql_vol:/var/lib/postgresql/data

volumes:
  postgresql_vol:
